require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TakamacchosController do

  # This should return the minimal set of attributes required to create a valid
  # Takamaccho. As you add validations to Takamaccho, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TakamacchosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all takamacchos as @takamacchos" do
      takamaccho = Takamaccho.create! valid_attributes
      get :index, {}, valid_session
      assigns(:takamacchos).should eq([takamaccho])
    end
  end

  describe "GET show" do
    it "assigns the requested takamaccho as @takamaccho" do
      takamaccho = Takamaccho.create! valid_attributes
      get :show, {:id => takamaccho.to_param}, valid_session
      assigns(:takamaccho).should eq(takamaccho)
    end
  end

  describe "GET new" do
    it "assigns a new takamaccho as @takamaccho" do
      get :new, {}, valid_session
      assigns(:takamaccho).should be_a_new(Takamaccho)
    end
  end

  describe "GET edit" do
    it "assigns the requested takamaccho as @takamaccho" do
      takamaccho = Takamaccho.create! valid_attributes
      get :edit, {:id => takamaccho.to_param}, valid_session
      assigns(:takamaccho).should eq(takamaccho)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Takamaccho" do
        expect {
          post :create, {:takamaccho => valid_attributes}, valid_session
        }.to change(Takamaccho, :count).by(1)
      end

      it "assigns a newly created takamaccho as @takamaccho" do
        post :create, {:takamaccho => valid_attributes}, valid_session
        assigns(:takamaccho).should be_a(Takamaccho)
        assigns(:takamaccho).should be_persisted
      end

      it "redirects to the created takamaccho" do
        post :create, {:takamaccho => valid_attributes}, valid_session
        response.should redirect_to(Takamaccho.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved takamaccho as @takamaccho" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takamaccho.any_instance.stub(:save).and_return(false)
        post :create, {:takamaccho => {  }}, valid_session
        assigns(:takamaccho).should be_a_new(Takamaccho)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takamaccho.any_instance.stub(:save).and_return(false)
        post :create, {:takamaccho => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested takamaccho" do
        takamaccho = Takamaccho.create! valid_attributes
        # Assuming there are no other takamacchos in the database, this
        # specifies that the Takamaccho created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Takamaccho.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => takamaccho.to_param, :takamaccho => { "these" => "params" }}, valid_session
      end

      it "assigns the requested takamaccho as @takamaccho" do
        takamaccho = Takamaccho.create! valid_attributes
        put :update, {:id => takamaccho.to_param, :takamaccho => valid_attributes}, valid_session
        assigns(:takamaccho).should eq(takamaccho)
      end

      it "redirects to the takamaccho" do
        takamaccho = Takamaccho.create! valid_attributes
        put :update, {:id => takamaccho.to_param, :takamaccho => valid_attributes}, valid_session
        response.should redirect_to(takamaccho)
      end
    end

    describe "with invalid params" do
      it "assigns the takamaccho as @takamaccho" do
        takamaccho = Takamaccho.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takamaccho.any_instance.stub(:save).and_return(false)
        put :update, {:id => takamaccho.to_param, :takamaccho => {  }}, valid_session
        assigns(:takamaccho).should eq(takamaccho)
      end

      it "re-renders the 'edit' template" do
        takamaccho = Takamaccho.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takamaccho.any_instance.stub(:save).and_return(false)
        put :update, {:id => takamaccho.to_param, :takamaccho => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested takamaccho" do
      takamaccho = Takamaccho.create! valid_attributes
      expect {
        delete :destroy, {:id => takamaccho.to_param}, valid_session
      }.to change(Takamaccho, :count).by(-1)
    end

    it "redirects to the takamacchos list" do
      takamaccho = Takamaccho.create! valid_attributes
      delete :destroy, {:id => takamaccho.to_param}, valid_session
      response.should redirect_to(takamacchos_url)
    end
  end

end
